In [3]:
import pandas as pd 
import calendar
import re

In [4]:
data = pd.read_csv("../data/raw/Mobile phone price.csv")

In [5]:
data.head()

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128 GB,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256 GB,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128 GB,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128 GB,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128 GB,8 GB,6.4,50 + 12.2,4614,799

In [6]:
data["Camera (MP)"].dtype

dtype('O')

In [7]:
data.columns

Index(['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

**In this section i chenged the column names because it has some spacing**

In [8]:
data = data.rename(columns={'Storage ': 'Storage'})

In [9]:
data = data.rename(columns={'RAM ': 'RAM'})

In [10]:
data = data.rename(columns={'Camera (MP)': 'Camera'})

In [11]:
data = data.rename(columns={'Battery Capacity (mAh)': 'Battery Capacity'})

In [12]:
data = data.rename(columns={'Price ($)': 'Price'})

In [13]:
data = data.rename(columns={'Screen Size (inches)': 'Screen Size'})

**We try to transform the values of each column**

In [14]:
data['Storage'].unique()

array(['128 GB', '256 GB', '64 GB', '32 GB', '128GB', '256GB', '64GB',
       '32GB', '256', '64', '128', '512', '32'], dtype=object)

In [15]:
data['Storage'] = data['Storage'].str.replace(r'[^0-9]', '', regex=True).astype(int)

In [16]:
data["RAM"].unique()

array(['6 GB', '12 GB', '8 GB', '4 GB', '3 GB', '2 GB', '4GB', '8GB',
       '6GB', '12GB', '3GB', '2GB', '5GB', '12', '3', '6', '8', '4', '16',
       '2'], dtype=object)

In [17]:
data['RAM'] = data['RAM'].astype(str).str.extract(r'(\d+)').astype(int)

In [18]:
data.head(15)

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799
5,Apple,iPhone 13,128,4,6.1,12 + 12,2815,799
6,Samsung,Galaxy Z Flip3,256,8,6.7,12 + 12,3300,999
7,Xiaomi,Poco X3 Pro,128,6,6.67,48 + 8 + 2 + 2,5160,249
8,Oppo,Reno6 Pro+ 5G,128,8,6.55,50 + 13 + 16 + 2,4500,699
9,Vivo,X70 Pro+,256,12,6.78,50 + 48 + 12 + 8,4500,1199
10,OnePlus,Nord CE 5G,128,6,6.43,64 + 8 + 2,4500,329
11,Samsung,Galaxy A52s 5G,128,6,6.5,64 + 12 + 5 + 5,4500,449
12,Realme,GT Neo2,128,8,6.62,64 + 8 + 2,5000,329
13,Apple,iPhone 12 Mini,64,4,5.4,12 + 12,2227,699
14,Oppo,Find X3 Pro,256,12,6.7,50 + 50 + 13 + 3,4500,1199

In [19]:
data["Camera"].dtype

dtype('O')

In [20]:
data["Camera"].unique()

array(['12 + 12 + 12', '108 + 10 + 10 + 12', '48 + 50 + 8 + 2',
       '64 + 8 + 5 + 2', '50 + 12.2', '12 + 12', '48 + 8 + 2 + 2',
       '50 + 13 + 16 + 2', '50 + 48 + 12 + 8', '64 + 8 + 2',
       '64 + 12 + 5 + 5', '50 + 50 + 13 + 3', '64 + 8 + 5',
       '64 + 12 + 12', '50 + 2 + 2', '48 + 2 + 2', '50 + 8 + 2 + 2',
       '48 + 5', '48 + 50 + 2', '108 + 8 + 5 + 2', '13 + 2 + 2', '13 + 2',
       '12', '48 + 5 + 2', '50 + 8 + 2', '64 + 8 + 2 + 2', '48 + 8 + 5',
       '64 + 8', '48 + 5 + 2 + 2', '50 + 2', '64 + 12 + 8 + 5', '64 + 2',
       '48 + 13 + 13', '12MP + 12MP', '64MP + 12MP + 12MP',
       '50MP + 8MP + 2MP', '50MP + 12MP', '48MP + 8MP + 2MP + 2MP',
       '64MP + 8MP + 2MP', '50MP + 48MP + 12MP + 8MP',
       '50MP + 16MP + 13MP + 2MP', '108MP + 16MP + 8MP', '48MP + 13MP',
       '12MP + 12MP + 12MP', '64MP + 13MP + 12MP', '64MP + 12MP + 8MP',
       '13MP + 5MP', '64MP + 12MP + 8MP + 5MP', '108MP + 8MP + 5MP + 2MP',
       '48MP + 50MP + 2MP', '50MP + 2MP + 2MP', '108MP + 8MP + 2MP',
       '48MP + 5MP + 2MP', '64MP + 5MP + 2MP + 2MP', '64MP + 12MP',
       '48MP + 50MP + 8MP', '50MP + 48MP + 48MP', '13MP + 2MP + 2MP',
       '13MP + 2MP', '8MP + 2MP', '12MP + 12MP + 8MP', '48MP + 2MP + 2MP',
       '64MP + 13MP + 5MP', '48MP + 8MP + 5MP', '12MP + 13MP',
       '50MP + 13MP + 16MP + 2MP', '50MP + 8MP + 2MP + 2MP', '50MP + 2MP',
       '48MP + 5MP', '64MP + 8MP + 2MP + 2MP', '64MP + 8MP + 5MP',
       '64MP + 8MP + 5MP + 5MP', '64MP + 12MP + 5MP + 5MP',
       '48MP + 8MP + 2MP', '48MP + 2MP', '108MP + 12MP + 10MP + 10MP',
       '64MP + 2MP', '64MP + 8MP', '64MP + 8MP + 5MP + 2MP', '50MP + 5MP',
       '48MP + 8MP + 5MP + 5MP', '108MP + 8MP + 2MP + 2MP',
       '48MP + 5MP + 2MP + 2MP', '13MP', '48MP + 8MP + 5MP + 2MP',
       '13MP + 5MP + 2MP', '8MP', '13MP + 5MP + 2MP + 2MP',
       '13MP + 8MP + 5MP + 2MP', '13MP + 8MP + 2MP + 2MP',
       '12MP + 2MP + 2MP', '13MP + 8MP + 2MP', '25MP + 8MP + 5MP',
       '108+12+12', '48+8+2+2', '12.2+16', '50+20+12+3D', '64+8+2+2',
       '64+12+5+5', '64+12+2+2', '12+12+12', '108+13+5', '48+2+2',
       '48+16+5+2', '13+8+5+2', '13+2+2', '48+5+2', '12+7',
       '108+10+10+12', '108+8+5+2', '50+16+13+2', '50+12+40+3D',
       '48+50+8+2', '48+8+2', '48+5+2+2', '12+12', '50+8+2+2',
       '50+8+16+2', '48+12+5', '48+48+8+5', '48+8+5', '40+40+8+3D',
       '48+12+13', '13+5+2', '48+8+5+2', '40+20+8+ToF', '12+12+8',
       '48+16+8', '16+8+5', '16+8+8+2', '12+64+12', '64+8+5',
       '50+40+12+3D', '108+48+12+3D', '48+50+2', '64+2+2', '48+13+12+2',
       '13+2', '48+8+5+5', '64+12+12', '108+48+12+0.3', '48+16+2',
       '48+13+8+2'], dtype=object)

In [21]:
def sum_camera_values(x):
    nums = re.findall(r'\d+\.?\d*', str(x))     # extract numbers (int + float)
    return sum(float(n) for n in nums)

data["Camera_TotalMP"] = data["Camera"].apply(sum_camera_values)

In [22]:
data

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price,Camera_TotalMP
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999,36.0
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199,140.0
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899,108.0
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279,79.0
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799,62.2
...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,88.0
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,60.0
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,36.0
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,71.0
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,65.0

In [23]:
data["Camera_Count"] = data["Camera"].str.findall(r'\d+\.?\d*').apply(len)

In [24]:
data["Has_3D"] = data["Camera"].str.contains("3D", case=False)

In [25]:
data["Has_ToF"] = data["Camera"].str.contains("ToF", case=False)

In [26]:
data["Screen Size"].unique()

array(['6.1', '6.8', '6.7', '6.67', '6.4', '6.55', '6.78', '6.43', '6.5',
       '6.62', '5.4', '6.2', '6.51', '6.6', '4.7', '6.58', '6.52', '6.44',
       '6.53', '6.56', '6.8 + 3.9', '4.5', '6.39', '5.9', '5.5', '6.81',
       '5.99', '6.82', '6.3', '6.22', '6', '6.35', '6.9', '6.76', '6.49',
       '6.72', '5.7', '6.47', '7.6 (unfolded)', '6.15', '6.57'],
      dtype=object)

In [27]:
data["Price"].unique()

array(['999', '1199', '899', '279', '799', '249', '699', '329', '449',
       '199', '299', '379', '179', '729', '599', '139', '189', '399',
       '259', '159', '229', '499', '129', '529', '369', '1099', '169',
       '99', '459', '239', '1299', '429', '659', '269', '359', '$799 ',
       '$399 ', '$699 ', '$329 ', '$999 ', '$549 ', '$1,299 ', '$899 ',
       '$449 ', '$319 ', '$269 ', '$349 ', '$279 ', '$249 ', '$299 ',
       '$969 ', '$1,199 ', '$149 ', '$139 ', '$99 ', '$199 ', '$169 ',
       '$499 ', '$179 ', '$219 ', '$229 ', '$239 ', '$109 ', '$189 ',
       '$389 ', '$309 ', '$369 ', '$129 ', '$849 ', '$469 ', '$209 ',
       '$119 ', '$339 ', '$429 ', '$159 ', '$379 ', '$289 ', '130', '749',
       '149', '969', '649', '349', '419', '1399', '1999', '119', '319',
       '1049'], dtype=object)

In [28]:
data['Price'] = (
    data['Price']
    .astype(str)                         # ensure string
    .str.replace(r'[^0-9\.]', '', regex=True)  # keep only digits + dot
    .astype(float)
)

In [29]:
data["Brand"].unique()

array(['Apple', 'Samsung', 'OnePlus', 'Xiaomi', 'Google', 'Oppo', 'Vivo',
       'Realme', 'Motorola', 'Nokia', 'Sony', 'LG', 'Asus', 'Blackberry',
       'CAT', 'Huawei'], dtype=object)

In [30]:
data = data.drop_duplicates()

In [31]:
data.isna().sum()

Brand               0
Model               0
Storage             0
RAM                 0
Screen Size         0
Camera              0
Battery Capacity    0
Price               0
Camera_TotalMP      0
Camera_Count        0
Has_3D              0
Has_ToF             0
dtype: int64

In [35]:
data.loc[:, 'Price_per_MP'] = data['Price'] / data['Camera_TotalMP']

In [42]:
data.loc[:, 'Camera_clean'] = (
    data['Camera']
    .astype(str)
    .str.replace("\n", " ")
    .str.replace("\r", " ")
    .str.strip()
)

In [44]:
data.loc[:, 'Main_Camera_MP'] = (
    data['Camera_clean']
    .str.extract(r'(\d+\.?\d*)')
    .astype(float)
)

In [50]:
data[['Camera', 'Camera_clean', 'Main_Camera_MP']].head(10)

               Camera        Camera_clean  Main_Camera_MP
0        12 + 12 + 12        12 + 12 + 12            12.0
1  108 + 10 + 10 + 12  108 + 10 + 10 + 12           108.0
2     48 + 50 + 8 + 2     48 + 50 + 8 + 2            48.0
3      64 + 8 + 5 + 2      64 + 8 + 5 + 2            64.0
4           50 + 12.2           50 + 12.2            50.0
5             12 + 12             12 + 12            12.0
6             12 + 12             12 + 12            12.0
7      48 + 8 + 2 + 2      48 + 8 + 2 + 2            48.0
8    50 + 13 + 16 + 2    50 + 13 + 16 + 2            50.0
9    50 + 48 + 12 + 8    50 + 48 + 12 + 8            50.0

In [46]:
# Normalize ALL whitespace including unicode
data.loc[:, 'Camera_clean'] = (
    data['Camera']
    .astype(str)
    .apply(lambda x: re.sub(r'\s+', ' ', x))  # convert ANY whitespace to single space
    .str.strip()
)

In [47]:
# Extract main camera MP correctly
data.loc[:, 'Main_Camera_MP'] = (
    data['Camera_clean']
    .str.extract(r'(\d+\.?\d*)')[0]
    .astype(float)
)

In [51]:
data.head(5)

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price,Camera_TotalMP,Camera_Count,Has_3D,Has_ToF,Price_per_MP,Main_Camera_MP,Camera_clean
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999.0,36.0,3,False,False,27.750000,12.0,12 + 12 + 12
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199.0,140.0,4,False,False,8.564286,108.0,108 + 10 + 10 + 12
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899.0,108.0,4,False,False,8.324074,48.0,48 + 50 + 8 + 2
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279.0,79.0,4,False,False,3.531646,64.0,64 + 8 + 5 + 2
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799.0,62.2,2,False,False,12.845659,50.0,50 + 12.2

In [49]:
data.to_csv("clean_mobile_data.csv", index=False)