**This is used to transform our data in python and make data cleaning procedure**

In [2]:
import pandas as pd 
import calendar

In [3]:
data = pd.read_csv("../data/raw/Global_Mobile_Prices_2025_Extended.csv")

In [4]:
data.head(5)

,brand,model,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,5g_support,os,processor,rating,release_month,year
0,Oppo,A98 111,855,16,128,108,6000,6.6,33,Yes,Android,Helio G99,3.8,February,2025
1,Realme,11 Pro+ 843,618,6,128,64,4500,6.9,100,Yes,Android,Tensor G4,4.4,August,2025
2,Xiaomi,Redmi Note 14 Pro 461,258,16,64,64,4000,6.8,44,Yes,Android,A18 Pro,4.1,March,2025
3,Vivo,V29e 744,837,6,512,48,4500,6.0,65,Yes,Android,Exynos 2400,4.1,August,2025
4,Apple,iPhone 16 Pro Max 927,335,12,128,200,5000,6.9,100,Yes,iOS,Dimensity 9300,3.5,February,2025

**First of all steps we have to check for existence of null values.**

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              1000 non-null   object
 1   model              1000 non-null   object
 2   price_usd          1000 non-null   int64
 3   ram_gb             1000 non-null   int64
 4   storage_gb         1000 non-null   int64
 5   camera_mp          1000 non-null   int64
 6   battery_mah        1000 non-null   int64
 7   display_size_inch  1000 non-null   float64
 8   charging_watt      1000 non-null   int64
 9   5g_support         1000 non-null   object
 10  os                 1000 non-null   object
 11  processor          1000 non-null   object
 12  rating             1000 non-null   float64
 13  release_month      1000 non-null   object
 14  year               1000 non-null   int64
dtypes: float64(2), int64(7), object(6)
memory usage: 117.3+ KB

In [6]:
data.isnull().sum()

brand                0
model                0
price_usd            0
ram_gb               0
storage_gb           0
camera_mp            0
battery_mah          0
display_size_inch    0
charging_watt        0
5g_support           0
os                   0
processor            0
rating               0
release_month        0
year                 0
dtype: int64

In [7]:
data.duplicated().sum()  #checking for duplicate values

np.int64(0)

In [8]:
data.dtypes

brand                 object
model                 object
price_usd              int64
ram_gb                 int64
storage_gb             int64
camera_mp              int64
battery_mah            int64
display_size_inch    float64
charging_watt          int64
5g_support            object
os                    object
processor             object
rating               float64
release_month         object
year                   int64
dtype: object

In [9]:
data['5g_support'] = data['5g_support'].map({'Yes': True, 'No': False}) #chage yes no to boolean true false

In [10]:
data['5g_support'].unique()

array([ True, False])

In [11]:
data['os'].unique()

array(['Android', 'iOS'], dtype=object)

In [12]:
data['release_month'].unique()

array(['February', 'August', 'March', 'May', 'April', 'November', 'July',
       'December', 'October', 'January', 'June', 'September'],
      dtype=object)

In [13]:
months_map = {m: i for i, m in enumerate(calendar.month_name) if m}
data['release_month_num'] = data['release_month'].map(months_map)

In [14]:
data[['release_month', 'release_month_num']].head(12)

   release_month  release_month_num
0       February                  2
1         August                  8
2          March                  3
3         August                  8
4       February                  2
5            May                  5
6          April                  4
7       November                 11
8           July                  7
9          March                  3
10         April                  4
11        August                  8

In [15]:
data['processor'].unique()[:20]

array(['Helio G99', 'Tensor G4', 'A18 Pro', 'Exynos 2400',
       'Dimensity 9300', 'Snapdragon 6 Gen 1', 'Snapdragon 8 Gen 3',
       'Snapdragon 7+ Gen 2'], dtype=object)

In [17]:
data.head(2)

,brand,model,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,5g_support,os,processor,rating,release_month,year,release_month_num
0,Oppo,A98 111,855,16,128,108,6000,6.6,33,True,Android,Helio G99,3.8,February,2025,2
1,Realme,11 Pro+ 843,618,6,128,64,4500,6.9,100,True,Android,Tensor G4,4.4,August,2025,8

In [21]:
data.describe()

,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,rating,year,release_month_num
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0,1000.000000
mean,813.478000,9.17200,402.880000,83.534000,5012.000000,6.380600,63.791000,4.229900,2025.0,6.356000
std,411.708367,4.32633,349.405893,62.504958,711.591429,0.496841,36.333751,0.439965,0.0,3.455895
min,101.000000,4.00000,64.000000,12.000000,4000.000000,5.500000,18.000000,3.500000,2025.0,1.000000
25%,449.250000,6.00000,128.000000,48.000000,4500.000000,6.000000,33.000000,3.800000,2025.0,3.000000
50%,822.000000,8.00000,256.000000,64.000000,5000.000000,6.400000,65.000000,4.200000,2025.0,6.000000
75%,1166.250000,12.00000,512.000000,108.000000,5500.000000,6.800000,100.000000,4.600000,2025.0,9.000000
max,1499.000000,16.00000,1024.000000,200.000000,6000.000000,7.200000,120.000000,5.000000,2025.0,12.000000

In [24]:
data[data["brand"]=='Apple']

,brand,model,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,5g_support,os,processor,rating,release_month,year,release_month_num
4,Apple,iPhone 16 Pro Max 927,335,12,128,200,5000,6.9,100,True,iOS,Dimensity 9300,3.5,February,2025,2
7,Apple,iPhone 16 Pro Max 232,1447,16,64,64,4500,6.7,33,True,iOS,Exynos 2400,4.7,November,2025,11
11,Apple,iPhone 14 397,1077,8,128,48,6000,7.1,120,False,iOS,Snapdragon 8 Gen 3,4.4,August,2025,8
22,Apple,iPhone 14 328,868,4,512,12,4500,7.2,44,False,iOS,Snapdragon 6 Gen 1,4.6,December,2025,12
33,Apple,iPhone 14 43,1058,4,256,50,4500,6.6,33,False,iOS,Snapdragon 8 Gen 3,4.4,June,2025,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,Apple,iPhone 16 Pro 356,259,12,1024,64,5500,5.6,44,True,iOS,Dimensity 9300,4.4,June,2025,6
931,Apple,iPhone 16 Pro 225,1441,16,128,200,4000,7.0,65,False,iOS,Snapdragon 8 Gen 3,4.4,October,2025,10
962,Apple,iPhone 16 Pro Max 533,1467,8,1024,64,5500,6.8,65,True,iOS,Dimensity 9300,3.7,July,2025,7
964,Apple,iPhone 16 Pro 99,993,4,128,64,5000,5.8,65,True,iOS,Dimensity 9300,4.6,September,2025,9
969,Apple,iPhone 14 59,1386,8,256,200,4000,5.6,65,True,iOS,Helio G99,3.9,September,2025,9

In [43]:
data[data['model'].str.contains("iPhone 16 Pro Max", case=False, na=False)].head(10)

,brand,model,price_usd,ram_gb,storage_gb,camera_mp,battery_mah,display_size_inch,charging_watt,5g_support,os,processor,rating,release_month,year,release_month_num,clean_model
4,Apple,iPhone 16 Pro Max 927,335,12,128,200,5000,6.9,100,True,iOS,Dimensity 9300,3.5,February,2025,2,iPhone 16 Pro Max
7,Apple,iPhone 16 Pro Max 232,1447,16,64,64,4500,6.7,33,True,iOS,Exynos 2400,4.7,November,2025,11,iPhone 16 Pro Max
39,Apple,iPhone 16 Pro Max 362,528,4,512,50,5500,7.2,120,False,iOS,Snapdragon 8 Gen 3,4.6,January,2025,1,iPhone 16 Pro Max
96,Apple,iPhone 16 Pro Max 413,168,4,256,48,4000,6.1,65,True,iOS,Snapdragon 7+ Gen 2,4.8,July,2025,7,iPhone 16 Pro Max
191,Apple,iPhone 16 Pro Max 615,367,4,512,200,4500,7.2,65,False,iOS,Dimensity 9300,4.2,April,2025,4,iPhone 16 Pro Max
209,Apple,iPhone 16 Pro Max 193,768,16,256,50,6000,6.6,33,False,iOS,Exynos 2400,3.8,June,2025,6,iPhone 16 Pro Max
220,Apple,iPhone 16 Pro Max 359,1417,12,512,48,5000,5.6,18,False,iOS,Helio G99,4.9,October,2025,10,iPhone 16 Pro Max
256,Apple,iPhone 16 Pro Max 22,625,6,1024,50,4500,6.5,65,True,iOS,Snapdragon 7+ Gen 2,4.3,August,2025,8,iPhone 16 Pro Max
280,Apple,iPhone 16 Pro Max 779,164,6,512,48,4000,6.6,33,False,iOS,Snapdragon 6 Gen 1,4.5,December,2025,12,iPhone 16 Pro Max
305,Apple,iPhone 16 Pro Max 361,1163,12,64,108,4000,7.0,100,False,iOS,A18 Pro,4.1,March,2025,3,iPhone 16 Pro Max

In [35]:
iphone_16_Pro_max= data[data['model'].str.contains("iPhone 16 Pro Max", case=False, na=False)]

In [38]:
avg_price_by_storage = iphone_16_Pro_max.groupby('storage_gb')['price_usd'].mean()
avg_price_by_storage

storage_gb
64      920.200000
128     852.000000
256     543.200000
512     791.625000
1024    828.666667
Name: price_usd, dtype: float64

In [39]:
avg_price_by_ram = iphone_16_Pro_max.groupby('ram_gb')['price_usd'].mean()

In [40]:
avg_price_by_ram

ram_gb
4      638.166667
6      463.666667
8     1144.333333
12     771.800000
16     772.000000
Name: price_usd, dtype: float64

In [61]:
data['clean_model'] = data['model'].str.replace(r"\s\d+$", "", regex=True)

In [62]:
data[data['clean_model'] == "iPhone 16 Pro Max"]['ram_gb'].unique()

array([12, 16,  4,  6,  8])

In [63]:
data[data['clean_model'] == "iPhone 16 Pro Max"]['display_size_inch'].unique()

array([6.9, 6.7, 7.2, 6.1, 6.6, 5.6, 6.5, 7. , 5.9, 7.1, 5.7, 6.2, 6.4,
       6.8])

In [64]:
data[data['clean_model'] == "iPhone 16 Pro Max"]['battery_mah'].unique()

array([5000, 4500, 5500, 4000, 6000])

In [65]:
data.to_csv("../data/cleaned/mobile_prices_cleaned.csv", index=False)