In [81]:
import pandas as pd 
import calendar
import re

In [48]:
data = pd.read_csv("../data/raw/Mobile phone price.csv")

In [71]:
data.head()

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price
0,Apple,iPhone 13 Pro,128,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8 GB,6.4,50 + 12.2,4614,799

In [50]:
data["Camera (MP)"].dtype

dtype('O')

In [66]:
data.columns

Index(['Brand', 'Model', 'Storage', 'RAM', 'Screen Size', 'Camera',
       'Battery Capacity', 'Price'],
      dtype='object')

**In this section i chenged the column names because it has some spacing**

In [57]:
data = data.rename(columns={'Storage ': 'Storage'})

In [59]:
data = data.rename(columns={'RAM ': 'RAM'})

In [61]:
data = data.rename(columns={'Camera (MP)': 'Camera'})

In [62]:
data = data.rename(columns={'Battery Capacity (mAh)': 'Battery Capacity'})

In [63]:
data = data.rename(columns={'Price ($)': 'Price'})

In [65]:
data = data.rename(columns={'Screen Size (inches)': 'Screen Size'})

**We try to transform the values of each column**

In [70]:
data['Storage'].unique()

array([128, 256,  64,  32, 512])

In [69]:
data['Storage'] = data['Storage'].str.replace(r'[^0-9]', '', regex=True).astype(int)

In [76]:
data["RAM"].unique()

array([ 6, 12,  8,  4,  3,  2,  5, 16])

In [75]:
data['RAM'] = data['RAM'].astype(str).str.extract(r'(\d+)').astype(int)

In [77]:
data.head(15)

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799
5,Apple,iPhone 13,128,4,6.1,12 + 12,2815,799
6,Samsung,Galaxy Z Flip3,256,8,6.7,12 + 12,3300,999
7,Xiaomi,Poco X3 Pro,128,6,6.67,48 + 8 + 2 + 2,5160,249
8,Oppo,Reno6 Pro+ 5G,128,8,6.55,50 + 13 + 16 + 2,4500,699
9,Vivo,X70 Pro+,256,12,6.78,50 + 48 + 12 + 8,4500,1199
10,OnePlus,Nord CE 5G,128,6,6.43,64 + 8 + 2,4500,329
11,Samsung,Galaxy A52s 5G,128,6,6.5,64 + 12 + 5 + 5,4500,449
12,Realme,GT Neo2,128,8,6.62,64 + 8 + 2,5000,329
13,Apple,iPhone 12 Mini,64,4,5.4,12 + 12,2227,699
14,Oppo,Find X3 Pro,256,12,6.7,50 + 50 + 13 + 3,4500,1199

In [79]:
data["Camera"].dtype

dtype('O')

In [80]:
data["Camera"].unique()

array(['12 + 12 + 12', '108 + 10 + 10 + 12', '48 + 50 + 8 + 2',
       '64 + 8 + 5 + 2', '50 + 12.2', '12 + 12', '48 + 8 + 2 + 2',
       '50 + 13 + 16 + 2', '50 + 48 + 12 + 8', '64 + 8 + 2',
       '64 + 12 + 5 + 5', '50 + 50 + 13 + 3', '64 + 8 + 5',
       '64 + 12 + 12', '50 + 2 + 2', '48 + 2 + 2', '50 + 8 + 2 + 2',
       '48 + 5', '48 + 50 + 2', '108 + 8 + 5 + 2', '13 + 2 + 2', '13 + 2',
       '12', '48 + 5 + 2', '50 + 8 + 2', '64 + 8 + 2 + 2', '48 + 8 + 5',
       '64 + 8', '48 + 5 + 2 + 2', '50 + 2', '64 + 12 + 8 + 5', '64 + 2',
       '48 + 13 + 13', '12MP + 12MP', '64MP + 12MP + 12MP',
       '50MP + 8MP + 2MP', '50MP + 12MP', '48MP + 8MP + 2MP + 2MP',
       '64MP + 8MP + 2MP', '50MP + 48MP + 12MP + 8MP',
       '50MP + 16MP + 13MP + 2MP', '108MP + 16MP + 8MP', '48MP + 13MP',
       '12MP + 12MP + 12MP', '64MP + 13MP + 12MP', '64MP + 12MP + 8MP',
       '13MP + 5MP', '64MP + 12MP + 8MP + 5MP', '108MP + 8MP + 5MP + 2MP',
       '48MP + 50MP + 2MP', '50MP + 2MP + 2MP', '108MP + 8MP + 2MP',
       '48MP + 5MP + 2MP', '64MP + 5MP + 2MP + 2MP', '64MP + 12MP',
       '48MP + 50MP + 8MP', '50MP + 48MP + 48MP', '13MP + 2MP + 2MP',
       '13MP + 2MP', '8MP + 2MP', '12MP + 12MP + 8MP', '48MP + 2MP + 2MP',
       '64MP + 13MP + 5MP', '48MP + 8MP + 5MP', '12MP + 13MP',
       '50MP + 13MP + 16MP + 2MP', '50MP + 8MP + 2MP + 2MP', '50MP + 2MP',
       '48MP + 5MP', '64MP + 8MP + 2MP + 2MP', '64MP + 8MP + 5MP',
       '64MP + 8MP + 5MP + 5MP', '64MP + 12MP + 5MP + 5MP',
       '48MP + 8MP + 2MP', '48MP + 2MP', '108MP + 12MP + 10MP + 10MP',
       '64MP + 2MP', '64MP + 8MP', '64MP + 8MP + 5MP + 2MP', '50MP + 5MP',
       '48MP + 8MP + 5MP + 5MP', '108MP + 8MP + 2MP + 2MP',
       '48MP + 5MP + 2MP + 2MP', '13MP', '48MP + 8MP + 5MP + 2MP',
       '13MP + 5MP + 2MP', '8MP', '13MP + 5MP + 2MP + 2MP',
       '13MP + 8MP + 5MP + 2MP', '13MP + 8MP + 2MP + 2MP',
       '12MP + 2MP + 2MP', '13MP + 8MP + 2MP', '25MP + 8MP + 5MP',
       '108+12+12', '48+8+2+2', '12.2+16', '50+20+12+3D', '64+8+2+2',
       '64+12+5+5', '64+12+2+2', '12+12+12', '108+13+5', '48+2+2',
       '48+16+5+2', '13+8+5+2', '13+2+2', '48+5+2', '12+7',
       '108+10+10+12', '108+8+5+2', '50+16+13+2', '50+12+40+3D',
       '48+50+8+2', '48+8+2', '48+5+2+2', '12+12', '50+8+2+2',
       '50+8+16+2', '48+12+5', '48+48+8+5', '48+8+5', '40+40+8+3D',
       '48+12+13', '13+5+2', '48+8+5+2', '40+20+8+ToF', '12+12+8',
       '48+16+8', '16+8+5', '16+8+8+2', '12+64+12', '64+8+5',
       '50+40+12+3D', '108+48+12+3D', '48+50+2', '64+2+2', '48+13+12+2',
       '13+2', '48+8+5+5', '64+12+12', '108+48+12+0.3', '48+16+2',
       '48+13+8+2'], dtype=object)

In [82]:
def sum_camera_values(x):
    nums = re.findall(r'\d+\.?\d*', str(x))     # extract numbers (int + float)
    return sum(float(n) for n in nums)

data["Camera_TotalMP"] = data["Camera"].apply(sum_camera_values)

In [89]:
data

,Brand,Model,Storage,RAM,Screen Size,Camera,Battery Capacity,Price,Camera_TotalMP,Camera_Count,Has_3D,Has_ToF
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999,36.0,3,False,False
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199,140.0,4,False,False
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899,108.0,4,False,False
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279,79.0,4,False,False
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799,62.2,2,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,88.0,3,False,False
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,60.0,4,False,False
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,36.0,3,False,False
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,71.0,4,False,False
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,65.0,3,False,False

In [84]:
data["Camera_Count"] = data["Camera"].str.findall(r'\d+\.?\d*').apply(len)

In [87]:
data["Has_3D"] = data["Camera"].str.contains("3D", case=False)

In [88]:
data["Has_ToF"] = data["Camera"].str.contains("ToF", case=False)

In [ ]:
data